<a href="https://colab.research.google.com/github/thummapalasuresh/ML_-projects/blob/main/Rock_Vs_MIne_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#From below Sonar data set we need to predict whether it is rock or mine

**Data collection and data processing**

In [ ]:
df= pd.read_csv("/content/Copy of sonar data.csv", header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [ ]:
df.shape

(208, 61)

In [ ]:
df.tail()

0       1       2       3       4       5       6       7       8   \
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[5 rows x 61 columns]

In [ ]:
df.describe()

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [ ]:
df.describe().transpose().head(10)

count      mean       std     min       25%      50%       75%     max
0  208.0  0.029164  0.022991  0.0015  0.013350  0.02280  0.035550  0.1371
1  208.0  0.038437  0.032960  0.0006  0.016450  0.03080  0.047950  0.2339
2  208.0  0.043832  0.038428  0.0015  0.018950  0.03430  0.057950  0.3059
3  208.0  0.053892  0.046528  0.0058  0.024375  0.04405  0.064500  0.4264
4  208.0  0.075202  0.055552  0.0067  0.038050  0.06250  0.100275  0.4010
5  208.0  0.104570  0.059105  0.0102  0.067025  0.09215  0.134125  0.3823
6  208.0  0.121747  0.061788  0.0033  0.080900  0.10695  0.154000  0.3729
7  208.0  0.134799  0.085152  0.0055  0.080425  0.11210  0.169600  0.4590
8  208.0  0.178003  0.118387  0.0075  0.097025  0.15225  0.233425  0.6828
9  208.0  0.208259  0.134416  0.0113  0.111275  0.18240  0.268700  0.7106

In [ ]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [ ]:
df.groupby(60).mean()

0         1         2         3         4         5         6   \
60                                                                         
M   0.034989  0.045544  0.050720  0.064768  0.086715  0.111864  0.128359   
R   0.022498  0.030303  0.035951  0.041447  0.062028  0.096224  0.114180   

          7         8         9   ...        50        51        52        53  \
60                                ...                                           
M   0.149832  0.213492  0.251022  ...  0.019352  0.016014  0.011643  0.012185   
R   0.117596  0.137392  0.159325  ...  0.012311  0.010453  0.009640  0.009518   

          54        55        56        57        58        59  
60                                                              
M   0.009923  0.008914  0.007825  0.009060  0.008695  0.006930  
R   0.008567  0.007430  0.007814  0.006677  0.007078  0.006024  

[2 rows x 60 columns]

**separate data and labels**

In [ ]:
x= df.drop(columns=60,axis=1)
y= df[60]

**Now training and split the data**

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.1, random_state=1)
x.shape, x_train.shape, x_test.shape

((208, 60), (187, 60), (21, 60))

**Model training ----> Logistic Regression**

In [ ]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

**Model Evaluation**

In [ ]:
#accuracy on training data
X_train_prediction = model.predict(x_train)
training_acc= accuracy_score(X_train_prediction,y_train)
print ("Accuracy score for traing data :",training_acc)

Accuracy score for traing data : 0.8556149732620321


In [ ]:
#accuracy on testing data
x_test_prediction= model.predict(x_test)
testing_acc= accuracy_score(x_test_prediction,y_test)
print ("Accuracy score for testing data :",testing_acc)

Accuracy score for testing data : 0.7142857142857143


**Making predictive system**

In [ ]:
input_data = (0.0307,0.0523,0.0653,0.0521,0.0611,0.0577,0.0665,0.0664,0.1460,0.2792,0.3877,0.4992,0.4981,0.4972,0.5607,0.7339,0.8230,0.9173,0.9975,0.9911,0.8240,0.6498,0.5980,0.4862,0.3150,0.1543,0.0989,0.0284,0.1008,0.2636,0.2694,0.2930,0.2925,0.3998,0.3660,0.3172,0.4609,0.4374,0.1820,0.3376,0.6202,0.4448,0.1863,0.1420,0.0589,0.0576,0.0672,0.0269,0.0245,0.0190,0.0063,0.0321,0.0189,0.0137,0.0277,0.0152,0.0052,0.0121,0.0124,0.0055)
type(input_data)


tuple

**changing the data into array**

In [ ]:
input_data_to_arr= np.asarray(input_data)
input_data_to_arr

array([0.0307, 0.0523, 0.0653, 0.0521, 0.0611, 0.0577, 0.0665, 0.0664,
       0.146 , 0.2792, 0.3877, 0.4992, 0.4981, 0.4972, 0.5607, 0.7339,
       0.823 , 0.9173, 0.9975, 0.9911, 0.824 , 0.6498, 0.598 , 0.4862,
       0.315 , 0.1543, 0.0989, 0.0284, 0.1008, 0.2636, 0.2694, 0.293 ,
       0.2925, 0.3998, 0.366 , 0.3172, 0.4609, 0.4374, 0.182 , 0.3376,
       0.6202, 0.4448, 0.1863, 0.142 , 0.0589, 0.0576, 0.0672, 0.0269,
       0.0245, 0.019 , 0.0063, 0.0321, 0.0189, 0.0137, 0.0277, 0.0152,
       0.0052, 0.0121, 0.0124, 0.0055])

**reshpaing the data**

In [ ]:
input_reshape= input_data_to_arr.reshape(1,-1)
input_reshape

array([[0.0307, 0.0523, 0.0653, 0.0521, 0.0611, 0.0577, 0.0665, 0.0664,
        0.146 , 0.2792, 0.3877, 0.4992, 0.4981, 0.4972, 0.5607, 0.7339,
        0.823 , 0.9173, 0.9975, 0.9911, 0.824 , 0.6498, 0.598 , 0.4862,
        0.315 , 0.1543, 0.0989, 0.0284, 0.1008, 0.2636, 0.2694, 0.293 ,
        0.2925, 0.3998, 0.366 , 0.3172, 0.4609, 0.4374, 0.182 , 0.3376,
        0.6202, 0.4448, 0.1863, 0.142 , 0.0589, 0.0576, 0.0672, 0.0269,
        0.0245, 0.019 , 0.0063, 0.0321, 0.0189, 0.0137, 0.0277, 0.0152,
        0.0052, 0.0121, 0.0124, 0.0055]])

**1st prediction**

In [ ]:
prediction = model.predict(input_reshape)
print(prediction)

['M']


In [ ]:
prediction = model.predict(input_reshape)
if (prediction == 'R'):
  print("it is rock")
else:
  print("mine")

mine


**2nd Prediction**

In [ ]:
input_data1 = (0.009,0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009,	0.009)
type(input_data1)

tuple

In [ ]:
input_data_to_arr1= np.asarray(input_data1)
input_data_to_arr1

array([0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
       0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
       0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
       0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
       0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
       0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
       0.009, 0.009, 0.009, 0.009, 0.009, 0.009])

In [ ]:
input_data_to_arr1_reshape = input_data_to_arr1.reshape(1,-1)
input_data_to_arr1_reshape

array([[0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
        0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
        0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
        0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
        0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
        0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009, 0.009,
        0.009, 0.009, 0.009, 0.009, 0.009, 0.009]])

In [ ]:
prediction1= model.predict(input_data_to_arr1_reshape)
prediction1

array(['R'], dtype=object)

In [ ]:
if (prediction1[0] == 'R'):
  print("the object is Rock")
else:
  print("the object is Mine")

the object is Rock
